# Generated by Django 5.0.7 on 2025-04-21 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_method', models.CharField(max_length=50)),
                ('barber', models.CharField(max_length=50)),
            ],
        ),
    ]
